package com.boris.fundingarbitrage;

import java.util.Set;
import java.util.concurrent.ExecutionException;

public class App {
//	static List<String> coins = List.of(
//					"ETH",
//					"SOL",
//					"WIF",
//					"PEPE",
//					"DOGE",
//					"XRP",
//					"0G",
//					"1INCH",
//					"1MBABYDOGE",
//					"2Z",
//					"4",
//					"A2Z",
//					"AAVE",
//					"ACE",
//					"ACH",
//					"ACTSOL",
//					"ACU",
//					"ADA",
//					"AERGO",
//					"AERO",
//					"AEVO",
//					"AGI",
//					"AGLD",
//					"AGT",
//					"AIN",
//					"AIOT",
//					"AIO",
//					"AI",
//					"AIXBT",
//					"AKE",
//					"ALCH",
//					"ALGO",
//					"ALICE",
//					"ALLO",
//					"ALPINE",
//					"ALT",
//					"ALU",
//					"ANIME",
//					"ANKR",
//					"APE",
//					"API3",
//					"APR",
//					"APT",
//					"ARB",
//					"ARC",
//					"ARIA",
//					"ARKM",
//					"ARK",
//					"ARPA",
//					"AR",
//					"ASP",
//					"ASR",
//					"ASTER",
//					"ASTR",
//					"ATH",
//					"ATOM",
//					"AT",
//					"AUCTION",
//					"AUDIO",
//					"A",
//					"AVAAI",
//					"AVA",
//					"AVAX",
//					"AVNT",
//					"AWE",
//					"AXL",
//					"AXS",
//					"AZTEC",
//					"B2",
//					"B3",
//					"BABY",
//					"BANANAS31",
//					"BANANA",
//					"BAND",
//					"BANK",
//					"BAN",
//					"BARD",
//					"BAS",
//					"BAT",
//					"BB",
//					"BCH",
//					"BDXN",
//					"BDX",
//					"BEAT",
//					"BEL",
//					"BERA",
//					"BIGTIME",
//					"BINANCELIFE",
//					"BIO",
//					"BIRB",
//					"BLAST",
//					"BLESS",
//					"BLUAI" // 92 coins
//	);

	private static final Set<String> coins = Set.of("SOL", "ETH", "XRP", "LTC", "ADA");

	static void main2(String[] args) throws Exception {

		Thread.sleep(40000);
	}

	static void main(String[] args) throws ExecutionException, InterruptedException {

	}
}
